### ISSUE TITLE
Git-sha should have length 7

### ISSUE THREAD

**Issue by duncdrum** [eeditiones/tuttle#11]
https://github.com/eeditiones/tuttle/blob/c58d66465eacb79d5f2147ce4ca34346e38a9d63/src/modules/app.xql#L296

here we force the value inside `gitsha.xml` to have length 6

also here

https://github.com/eeditiones/tuttle/blob/c58d66465eacb79d5f2147ce4ca34346e38a9d63/src/modules/github.xql#L67

and here 

https://github.com/eeditiones/tuttle/blob/c58d66465eacb79d5f2147ce4ca34346e38a9d63/src/modules/github.xql#L81

and here 

https://github.com/eeditiones/tuttle/blob/c58d66465eacb79d5f2147ce4ca34346e38a9d63/src/modules/gitlab.xql#L117

and here 

https://github.com/eeditiones/tuttle/blob/c58d66465eacb79d5f2147ce4ca34346e38a9d63/src/modules/gitlab.xql#L138

and a few more … 

TODO: add tests
TODO: incomplete but git search to the rescue

**Comment by line-o** [comment]
This command will always output 7 leading characters of the git sea `git describe --tags --always HEAD`
