### ISSUE TITLE
failing tests due to GitHub authentication failure

### ISSUE THREAD

**Issue by line-o** [eeditiones/tuttle#16]
A significant portion of the tests are not running in CI due to the environment variable
`tuttle_token_tuttle_sample_data` is 
- not being properly set in docker container
- cannot be read from existdb in docker container

I did check and can confirm that the tests do run on a local machine when the env variable is set.

**Comment by line-o** [comment]
@duncdrum can you advise how to start a docker container thus that the existdb process "sees" an environment variable that is set in a GHA?

https://github.com/eeditiones/tuttle/blob/c58d66465eacb79d5f2147ce4ca34346e38a9d63/.github/workflows/node.js.yml#L17-L18

```yaml
        env: 
          tuttle_token_tuttle_sample_data: ${{ secrets.tuttle_token_tuttle_sample_data }} 
```

**Comment by duncdrum** [comment]
Top of my head I'm clueless. This used to work re visibility and i don't see any changes between the last succesfull CI run and those here now that would explain the difference. TBH i m a bit surprised that it worked, looking at it.

**Comment by line-o** [comment]
But it does! :)
See #17
